// Re-export Phosphor Icons for enterprise-grade iconography
// Phosphor Icons - MIT License, 7000+ icons, professional design
// All icons sourced from @phosphor-icons/core assets — zero hand-written SVG
export {
  PhHouse as IconHome,
  PhClockCounterClockwise as IconTimeline,
  PhCamera as IconCamera,
  PhMapTrifold as IconMap,
  PhHeart as IconCollection,
  PhUser as IconProfile,
  PhUser as IconUser,
  PhPencilSimple as IconEdit,
  PhTrash as IconDelete,
  PhHeart as IconFavorite,
  PhShareNetwork as IconShare,
  PhDotsThreeVertical as IconMore,
  PhArrowLeft as IconBack,
  PhPlus as IconPlus,
  PhCheck as IconCheck,
  PhX as IconX,
  PhClock as IconClock,
  PhMapPin as IconLocation,
  PhMapPin as IconMapPin,
  PhImage as IconImage,
  PhStamp as IconStampClassic,
  PhTreePalm as IconStampNature,
  PhBuildings as IconStampCity,
  PhGlobeHemisphereWest as IconGlobe,
  PhBookOpen as IconBookOpen,
  PhRocket as IconRocket,
  PhCheckCircle as IconCheckCircle,
  PhClipboardText as IconClipboardList,
  PhAirplaneTilt as IconAirplane,
  PhCrown as IconCrown,
  PhEnvelope as IconEnvelope,
  PhArticle as IconArticle,
  // Stamp design icons — mapped from Phosphor Icons core assets
  PhColumns as IconStampCulture,
  PhWaves as IconStampSea,
  PhSun as IconStampSunset,
  // Brand icon — mailbox for splash screen
  PhMailbox as IconMailbox,
  // Profile page icons
  PhInfo as IconInfo,
  PhArrowCounterClockwise as IconReset,
  PhShieldCheck as IconShield,
  PhFileText as IconFileText,
  PhGear as IconSettings,
  PhSignOut as IconSignOut,
  PhCaretRight as IconCaretRight,
} from '@phosphor-icons/vue'
